version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_serbin
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: serbin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  python-app:
    build:
      context: ./python
    container_name: python_app
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:

